# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f9ee1f69b9b49ec337aa9f18c71627f3d216fae13951fdaf0e07e893a7b2af6fe3521c48381f1c54c2eac979156a1ffafa7d71bb21ee22bae77d635f56900237

test:
  secret_key_base: 3b5017fa456639a106ceb96ddd8ad7b6589b4b5ce6baf963937c6f713e81257b0f63099b545576f5d3472cb25aff7d1437bd5bd87ea5754d294afe4d1b94bbcd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
